version: "3"
services:
    bot:
        image: docker.io/procsiab/ntvpromo:v1.13-aarch64
        container_name: ntvpromo
        hostname: ntvpromo
        volumes:
            - ./app/data:/app/data:z
            - ./.secrets:/auth:z
        restart: unless-stopped
        networks:
            - ntvpromo_exposed
        env:
            - TZ="Europe/Rome"
