version: "3"
services:
    bot:
        image: procsiab/ntvpromo:1.0-aarch64
        container_name: ntvpromo
        hostname: ntvpromo
        volumes:
            - ./app:/app:z
            - ./.secrets:/secrets:z
        restart: unless-stopped
        networks:
            - ntvpromo_exposed
networks:
    ntvpromo_exposed:
        external: true
