version: "3"
services:
    bot:
        image: procsiab/ntvpromo:amd64
        volumes:
            - ./app:/app:z
            - ./.secrets:/secrets:z
        network_mode: bridge
        restart: unless-stopped
