FROM arm32v7/python:3.9.5-alpine3.13
LABEL maintainer "Lorenzo Prosseda <lerokamut@gmail.com>"

COPY qemu-arm-static /usr/bin/

ADD ./app /app

RUN pip install -I -r /app/requirements.txt

WORKDIR /app
VOLUME ["/app"]

RUN rm -rf /usr/bin/qemu-arm-static

ENTRYPOINT ["python3", "main.py"]
