version: "3"
services:
    bot:
        image: procsiab/ntvpromo:1.4-aarch64
        container_name: ntvpromo
        hostname: ntvpromo
        volumes:
            - ./app/data:/app/data:z
            - ./.secrets:/auth:z
        restart: unless-stopped
        networks:
            - ntvpromo_exposed
        env:
            - TZ="Europe/Rome"
networks:
    ntvpromo_exposed:
        external: true
